title: Offensive AI Compilation
description: >- # this means to ignore newlines until "baseurl:"
  🤖 Here you will find a curated list of useful resources that cover Offensive AI. 
theme: jekyll-theme-cayman
jekyll_admin:
  hidden_links:
    - posts
    - pages
    - staticfiles
    - datafiles
    - configuration
plugins:
  - jekyll-seo-tag